//! PuTTY `.ppk` keys (v2 and v3) against the OpenSSH originals they were made
//! from. The fixtures in `fixtures/ppk/` are throwaway keys: each `<alg>.openssh`
//! was generated by `ssh-keygen` and converted by PuTTY's own `puttygen` into
//! `<alg>-v2.ppk` and `<alg>-v3.ppk`, and `ed25519-encrypted.ppk` has a
//! passphrase. A `.ppk` must load as exactly the key it was made from, and
//! sign so the OpenSSH public key verifies it.

#![allow(missing_docs)]

use std::path::PathBuf;

use troved::ssh_agent::keys::{parse_private_key, ppk_to_openssh, ParseError};

fn fixture(name: &str) -> Vec<u8> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/ppk")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()))
}

#[test]
fn every_ppk_loads_as_the_key_it_was_made_from() {
    for alg in ["ed25519", "rsa", "ecdsa"] {
        let original = parse_private_key(&fixture(&format!("{alg}.openssh")), "k").unwrap();
        for version in ["v2", "v3"] {
            let name = format!("{alg}-{version}.ppk");
            let loaded =
                parse_private_key(&fixture(&name), "k").unwrap_or_else(|e| panic!("{name}: {e}"));
            assert_eq!(loaded.public_blob, original.public_blob, "{name}");
            assert_eq!(loaded.algorithm_name(), original.algorithm_name(), "{name}");
        }
    }
}

#[test]
fn a_ppk_converts_to_openssh_pem() {
    for alg in ["ed25519", "rsa", "ecdsa"] {
        let original = parse_private_key(&fixture(&format!("{alg}.openssh")), "k").unwrap();
        let pem = ppk_to_openssh(&fixture(&format!("{alg}-v3.ppk")), "me@host").unwrap();
        assert!(
            pem.starts_with("-----BEGIN OPENSSH PRIVATE KEY-----"),
            "{alg}"
        );
        let again = parse_private_key(pem.as_bytes(), "k").unwrap();
        assert_eq!(again.public_blob, original.public_blob, "{alg}");
    }
}

#[test]
fn an_encrypted_ppk_is_refused_with_a_fix() {
    let err = parse_private_key(&fixture("ed25519-encrypted.ppk"), "k").unwrap_err();
    assert!(matches!(err, ParseError::PpkEncrypted), "{err:?}");
    assert!(err.to_string().contains("PuTTYgen"), "{err}");
}

#[test]
fn a_damaged_ppk_fails_its_mac() {
    let mut bytes = fixture("ed25519-v3.ppk");
    let text = String::from_utf8(bytes.clone()).unwrap();
    // Change the comment: the key still parses, but the MAC covers it.
    bytes = text
        .replace("Comment: ppk-ed25519", "Comment: ppk-ed25519x")
        .into_bytes();
    let err = parse_private_key(&bytes, "k").unwrap_err();
    assert!(err.to_string().contains("MAC"), "{err}");
}

#[test]
fn a_ppk_key_signs_exactly_like_the_original() {
    // Ed25519, RSA PKCS#1 v1.5 and RFC 6979 ECDSA are all deterministic, so a
    // correctly converted key gives byte-identical signatures. A matching
    // public key alone wouldn't catch RSA's private fields in the wrong order.
    const SSH_AGENT_RSA_SHA2_256: u32 = 2;
    for alg in ["ed25519", "rsa", "ecdsa"] {
        let original = parse_private_key(&fixture(&format!("{alg}.openssh")), "k").unwrap();
        for version in ["v2", "v3"] {
            let loaded = parse_private_key(&fixture(&format!("{alg}-{version}.ppk")), "k").unwrap();
            let data = b"trove ppk signing check";
            assert_eq!(
                loaded.sign(data, SSH_AGENT_RSA_SHA2_256).unwrap(),
                original.sign(data, SSH_AGENT_RSA_SHA2_256).unwrap(),
                "{alg}-{version}"
            );
        }
    }
}

#[test]
fn a_ppk_attachment_in_a_vault_is_served() {
    // KeeAgent on Windows often keeps .ppk files; both the KeeAgent-named
    // attachment and a plain content scan must pick one up.
    let tmp = tempfile::tempdir().unwrap();
    let path = tmp.path().join("v.kdbx");
    let mut v = trove_core::Vault::create(&path, "pw").unwrap();
    let named = v.add_entry("Windows/putty").unwrap();
    v.attach_binary(&named, "key.ppk", &fixture("ed25519-v3.ppk"))
        .unwrap();
    let settings = troved::ssh_agent::keeagent::settings_xml("key.ppk");
    v.attach_binary(
        &named,
        troved::ssh_agent::keeagent::ATTACHMENT_NAME,
        &settings,
    )
    .unwrap();
    let scanned = v.add_entry("Windows/scanned").unwrap();
    v.attach_binary(&scanned, "id", &fixture("rsa-v2.ppk"))
        .unwrap();

    let keys = troved::handler::load_ssh_keys_from_vault_filtered(&v, None);
    let mut comments: Vec<&str> = keys.iter().map(|k| k.comment.as_str()).collect();
    comments.sort_unstable();
    assert_eq!(comments.len(), 2, "{comments:?}");
    assert!(comments[0].starts_with("Windows/putty"), "{comments:?}");
    assert_eq!(comments[1], "Windows/scanned");
}
